name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "21"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install required platform
        run: |
          yes | sdkmanager "platforms;android-33" "build-tools;33.0.2"
      - name: Verify Android SDK installation
        run: |
          sdkmanager --list | grep "build-tools;33.0.2"
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      - uses: ilharp/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias: ${{ secrets.KEYSTORE_ALIAS }}
      - name: Upload Packages
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: eUICC Probe
          path: ${{ steps.sign_app.outputs.signedFile }}
