
name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "21"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: 33.0.2
          ndk: 21.4.7075529

      - name: Verify Android SDK installation
        run: |
          sdkmanager --list || true
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"

      - name: Install required platform tools
        run: sdkmanager "platforms;android-33" "build-tools;33.0.2"

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - uses: ilharp/sign-android-release@v1 # Or use @nightly
        name: Sign app APK
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.KEYSTORE }}
          keyAlias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          buildToolsVersion: 33.0.0

      - name: Upload Packages
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Signed app bundle
          path: ${{ steps.sign_app.outputs.signedFile }}
